spring.application.name=sate-uniajc
server.port=8080

# Demo local con H2. No requiere instalar MySQL.
spring.datasource.url=jdbc:h2:mem:satedb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true

spring.jackson.serialization.write-dates-as-timestamps=false
